import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/ui/shared/components/navbar";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <Toaster
          position="top-center"
          toastOptions={{
            success: {
              style: {
                background: "#4CAF50",
                color: "#FFFFFF",
              },
            },
            error: {
              style: {
                background: "#EFEFEF",
                color: "#BE2921",
              },
            },
          }}
        />
        {children}
      </body>
    </html>
  );
}
